# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48a6edbbf5d1ffe5fea89990a642edc8cefb55290d18d6494885fb46a9732dc643ada31b1a0a390654c3efd3f4df56d09b78e0255585264ebac119946909196d

test:
  secret_key_base: ade9bde87f34a6a73e105e5a9a8a1e4e74fbb7f5a584200d5a980ef1b6569c9a3316fb8fcd6fbf9b54107383be6502781fba0ad4e9dbba9c94ece30bcada9c64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
